<Project>

  <PropertyGroup>

    <EnlistmentRoot>$(MSBuildThisFileDirectory)</EnlistmentRoot>
    <MajorVersion>1</MajorVersion>
    <MinorVersion>0</MinorVersion>

    <Company>Microsoft Corp</Company>
    <Copyright>%A9 Halid Cisse. All rights reserved.</Copyright>

    <MajorVersion>1</MajorVersion>
    <MinorVersion>0</MinorVersion>

    <ArtifactsDir>$(MSBuildThisFileDirectory)\__artifacts\__bin\$(MSBuildProjectName)</ArtifactsDir>
    
    <BaseOutputPath>$(ArtifactsDir)</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)\__artifacts\__obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    
    <PublishDir>$(MSBuildThisFileDirectory)\__artifacts\__publish\$(MSBuildProjectName)</PublishDir>
    
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <EnlistmentRoot>$(MSBuildThisFileDirectory)</EnlistmentRoot>
    <RootNamespace>Tooling.$(MSBuildProjectName)</RootNamespace>

    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>

    <AppTargetFramework>net5.0</AppTargetFramework>
    <NetCoreVer>5.0.102</NetCoreVer>
  </PropertyGroup>
</Project>